### ISSUE TITLE
Error when setting up plugin

### ISSUE THREAD

**Issue by bschilt** [drutiny/page-speed-insights#2]
The README says to set up the page speed credentials like this:

```drutiny plugin:setup page-speed-insights```

The following error is displayed:

```
In AuthenticateCommand.php line 62:

  Cannot find schema for page-speed-insights.

plugin:setup <namespace>
```

The credential schema is defined as `pagespeedinsights` in `drutiny-config.yml`, not `page-speed-insights`. As it stands now the correct command would be to run 

```drutiny plugin:setup pagespeedinsights```

Either update the README with the correct schema name, or adjust the schema name in `drutiny-config.yml` to be `page-speed-insights`

**Comment by thomaslafon** [comment]
Fixed Credential schema in drutiny-config.yml to match current plugin name.
